version: '3'
services:
  database:
    image: mongo
    ports:
      - 27017:27017
  backend:
    image: mayank31313/ior-backend:v1
    ports:
      - 8080:8080
    depends_on:
      - database
    environment: 
      - mongo.uri=mongodb://database:27017/?readPreference=primary
  tunnel:
    image: mayank31313/socket-server:v1
    environment: 
      - mongo.uri=mongodb://database:27017/?readPreference=primary
      - createDefaultDevices=true
    ports: 
      - 5001:5001
      - 8000:8000
  kms:
    image: kurento/kurento-media-server
    ports:
      - 8888:8888
  video:
    image: mayank31313/video-server:v1
    depends_on:
      - kms
      - database
    ports:
      - 8081:8081
    environment: 
      - mongo.uri=mongodb://database:27017/?readPreference=primary
      - kurento.url=ws://kms:8888/kurento