version: '3'
services:
  database:
    image: mongo
  tunnel:
    image: mayank31313/socket-server:v1
    environment: 
      - mongo.uri=mongodb://database:27017/?readPreference=primary
      - createDefaultDevices=true
    ports: 
      - 5001:5001
      - 8000:8000